repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: forbid-crlf
        exclude: "tests/snapshots/.*"
      - id: remove-crlf
        exclude: "tests/snapshots/.*"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "tests/snapshots/.*"
      - id: end-of-file-fixer
        exclude: "tests/snapshots/.*"
      - id: check-merge-conflict
        exclude: "tests/snapshots/.*"
      - id: check-yaml
        exclude: "tests/snapshots/.*"
        args: [ --unsafe ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: "tests/snapshots/.*"
        args: [ "--filter-files" ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: "tests/snapshots/.*"
        language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: "tests/snapshots/.*"
        additional_dependencies: [ flake8-typing-imports==1.10.0 ]
