name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, "*" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker compose build tests-with-coverage --quiet
          docker compose pull
      - name: Run Tests via Docker
        run: |
          docker compose --env-file .env.docker run tests-with-coverage
      - name: Show Test Logs if tests failed
        if: ${{ failure() }}
        run: docker compose logs
